### PR TITLE
Add precompilation

### PR DESCRIPTION
**Pull request by scidom**

### CODE REVIEW

**Comment by scidom** [comment]
@kmsquire @ranjanan @yuyichao @ViralBShah, I would be grateful if you could help me with the merging of this PR, as I want to add precompilation to Klara, which in turns requires precompilation for Formatting. Your help is appreciated.

**Comment by scidom** [comment]
@ararslan

**Comment by scidom** [comment]
Thanks, @ararslan! 👍 

It would be great to submit this on metadata too; if it causes a lot of hassle, I would be happy to contribute if I am given access, or you may attobot it if this would be more appropriate.

**Comment by ararslan** [comment]
https://github.com/JuliaLang/METADATA.jl/pull/8618

**Pull request merged**
