### PR TITLE
Overflow when rounding

### PR DESCRIPTION
**Pull request by jmkuhn**
Partially addresses #84

### CODE REVIEW

**Comment by ScottPJones** [comment]
When I tried to test this change, all I get is errors:

```
fmt("+11.3e", 1.0e-309)

Stacktrace:
 [1] trunc at ./float.jl:703 [inlined]
 [2] trunc at ./float.jl:359 [inlined]
 [3] _pfmt_floate(::Base.GenericIOBuffer{Array{UInt8,1}}, ::Char, ::Int64, ::Float64, ::Int64, ::Int64, ::Char) at /Users/scott/.julia/packages/Formatting/LU9hd/src/fmtcore.jl:204
```

Also, looking at the code, I don't see how it can give a correct answer, because it doesn't adjust the value of `e` that is printed out.

**Comment by jmkuhn** [comment]
What Julia version and OS are you using?

For the issue that this PR fixes, `e` is correct but `u` overflows to `Inf`
```
julia> ax = 1.0e-309
1.0e-309

julia> rax = round(ax, sigdigits = 3 + 1)
1.0e-309

julia> e = floor(Integer, log10(rax))  # exponent
-309

julia> u = rax * exp10(-e)  # significand
Inf

julia> i = 1
1

julia> u = 10^i * rax * exp10(-e - i)
1.000000000000002
```

**Comment by ScottPJones** [comment]
macOS 10.15.6 Catalina

`  | | |_| | | | (_| |  |  Version 1.6.0-DEV.952 (2020-09-17)
 _/ |\__'_|_|_|\__'_|  |  Commit 4ef8313c94 (0 days old master)
|__/                   |

julia> using Formatting

julia> fmt("+11.3e", 1.0e-309)
ERROR: InexactError: trunc(Int64, Inf)
Stacktrace:
  [1] trunc
    @ ./float.jl:703 [inlined]
  [2] trunc
    @ ./float.jl:359 [inlined]
  [3] _pfmt_floate(out::IOBuffer, sch::Char, zs::Int64, u::Float64, prec::Int64, e::Int64, ec::Char)
    @ Formatting ~/.julia/packages/Formatting/LU9hd/src/fmtcore.jl:204
  [4] _pfmt_e(out::IOBuffer, fs::FormatSpec, x::Float64)
    @ Formatting ~/.julia/packages/Formatting/LU9hd/src/fmtcore.jl:251
  [5] printfmt(io::IOBuffer, fs::FormatSpec, x::Float64)
    @ Formatting ~/.julia/packages/Formatting/LU9hd/src/fmtspec.jl:190`

**Comment by ScottPJones** [comment]
OK, I see now what the for loop is attempting to do, but, why do it as a for loop?
Since you know in advance that any value for e below -308 will end up with exp10(-e) returning `Inf`,
you can simply calculate how much rax must be multiplied by 10^i to keep that from happening.
Also, this code has a problem with 10^i will overflow silently if i > 18.

**Comment by jmkuhn** [comment]
I'm unable to reproduce your issue, but I'll keep looking at it.
```
% sw_vers 
ProductName:	Mac OS X
ProductVersion:	10.15.6
BuildVersion:	19G2021

julia> VERSION
v"1.6.0-DEV.961"

julia> using Formatting

julia> fmt("+11.3e", 1.0e-309)
"+1.000e-309"
```

**Comment by ScottPJones** [comment]
It looks like the problem is fairly simply: you need to set up a new version of Formatting, it is picking up v0.4.1, from September 2019, not the latest version in master.

**Pull request merged**
